- name: BIG-IP SETUP
  hosts: 10.1.10.83
  connection: local
  gather_facts: false
  vars:
    auth:
      server: "{{inventory_hostname}}"
      user: "admin"
      password: "Consys1994"
      server_port: 443
      no_f5_teem: false
      validate_certs: false
      ######

  tasks:
    - name: Create a Node
      f5networks.f5_modules.bigip_node:
        provider: "{{auth}}"
        host: 10.20.30.42
        name: 10.20.30.42
