- name: BIG-IP SETUP
  hosts: bigip41
  connection: local
  gather_facts: false

  tasks:

    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          # user: "{{ f5_admin_user }}"
          # password: "{{ f5_admin_password }}"
          server_port: "{{ f5_admin_port }}"
          validate_certs: false
    - name: Create a Node
      f5networks.f5_modules.bigip_command:
        host: 10.20.30.40
        name: 10.20.30.40
